### ISSUE TITLE
API broke again

### ISSUE THREAD

**Issue by drallgood** [fleinze/vienna-smartmeter#2]
I think something changed again. I'm getting 500s on `https://service.wienernetze.at/rest/smp/1.0/w/user/profile` 
From the website I can see a slightly different endpoint being called now `https://service.wienernetze.at/sm/api/user/profile`

**Comment by ghhausi** [comment]
You may read https://github.com/platysma/vienna-smartmeter/issues/176#issuecomment-2116994268 for the fix

**Comment by ghhausi** [comment]
API Changed again ???  Anyone working on it ?

see issue (https://github.com/platysma/vienna-smartmeter/issues/177)

**Comment by fleinze** [comment]
Fixed in #4

**Comment by ghhausi** [comment]
Thank you!
